#!/usr/bin/env python3
# -*-Python-*-

import re, sys

data = open(sys.argv[1]).read()

data = re.sub(r'(?m)[ \t]+$', '', data.rstrip())

data = re.sub(r'(\r?\n)(?:\r?\n)+\f', '\\1\f', data)

sys.stdout.write(data)




